# Generated by Django 5.1.4 on 2025-01-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmapping',
            name='short_code',
        ),
        migrations.AddField(
            model_name='urlmapping',
            name='short_name',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
